<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample events data with _id fields
        $events = [
            [
                'id' => 1,
                '_id' => '686dd7a16747c7b7cf5fb546',
                'eventId' => '34436569',
                'exEventId' => '10b7f4b14070ec5004e7412b2039b78d',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Abdullah Mason v Sam Noakes',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-07-09 02:44:49',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 2,
                '_id' => '686dd7a402b374ffd861ba46',
                'eventId' => '34471076',
                'exEventId' => 'c9f7c08f7cd07ab5c108e33eb1831e54',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Brian Norman Jr v Devin Haney',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-07-09 02:44:52',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 3,
                '_id' => '686dd7a53400437f0b30216e',
                'eventId' => '34481170',
                'exEventId' => '6a8550a6b8d3bb3728b8bfe61e17b7cf',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'David Benavidez v Anthony Yarde',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-07-09 02:44:53',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 4,
                '_id' => '686dd7a8b1fff3055b0a4063',
                'eventId' => '34497168',
                'exEventId' => 'd4cd5d927dcc104d550081bb5248a4ce',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Jesse Rodriguez v Fernando Daniel Martinez',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-07-09 02:44:56',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 5,
                '_id' => '68d280873ed49c810a842de8',
                'eventId' => '34589377',
                'exEventId' => '718328b231f0bb73deef04130b446f4f',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Junaid Bostan v Bilal Fawaz',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:07',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 6,
                '_id' => '68d28088141766fa4f20c54d',
                'eventId' => '34713137',
                'exEventId' => 'a40eed7eac02ad9490f7c821958a9029',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Royston Barney-Smith v Danny Quartermaine',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:08',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 7,
                '_id' => '68d2809a5ed00f7015d6d933',
                'eventId' => '34662420',
                'exEventId' => '6ddece57f04f1281ea9e619aa239715b',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Alexis Barriere v Guido Vianello',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:26',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 8,
                '_id' => '68d2809a15b86e331f768020',
                'eventId' => '34604856',
                'exEventId' => 'd2cfd0f06499cf89c6ff45374c36e501',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Bradley Rea v Lyndon Arthur',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:26',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 9,
                '_id' => '68d2809b141766fa4f20c551',
                'eventId' => '34604855',
                'exEventId' => 'efb71986e4ac9a148a5ceb46f6cba710',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Daniel Lapin v Troy Jones',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:27',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 10,
                '_id' => '68d2809bd43bb8151af93d9b',
                'eventId' => '34713134',
                'exEventId' => 'cbf3bbde79345ebc5015f86c78e19b65',
                'sportId' => '6',
                'tournamentsId' => '1576402161',
                'tournamentsName' => 'Boxing Matches',
                'eventName' => 'Denzel Bentley v Endry Saavedra',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-23 11:12:27',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            // Cricket Events
            [
                'id' => 11,
                '_id' => '68db8389fb9e94804b51d7df',
                'eventId' => '346913081209',
                'exEventId' => 'c5531e619c35977a32287c1abda56a1b',
                'sportId' => '4',
                'tournamentsId' => '34644908',
                'tournamentsName' => "ICC Women's Cricket World Cup",
                'eventName' => "ICC Women's Cricket World Cup",
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-30 07:15:21',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 12,
                '_id' => '68dbfefcf165840e0e0e33d6',
                'eventId' => '34792861',
                'exEventId' => 'cce65a4f0a906aca34160b9063648f2d',
                'sportId' => '4',
                'tournamentsId' => '1576334505',
                'tournamentsName' => 'Test Matches',
                'eventName' => 'Pakistan v South Africa',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-09-30 16:02:04',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 13,
                '_id' => '68e26ab2018482ca994236a6',
                'eventId' => '34807931',
                'exEventId' => '4609acfd88adb979a040153899b44cd7',
                'sportId' => '4',
                'tournamentsId' => '1576334505',
                'tournamentsName' => 'Test Matches',
                'eventName' => 'India v West Indies',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-05 12:55:14',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 14,
                '_id' => '68e4b62f2176b5c6b444ad63',
                'eventId' => '34816855',
                'exEventId' => 'b6d98819628995e4a938015c764dbfe4',
                'sportId' => '4',
                'tournamentsId' => '1576028057',
                'tournamentsName' => 'International Twenty20 Matches',
                'eventName' => 'Namibia v South Africa',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-07 06:41:51',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 15,
                '_id' => '68e5fe878c60f2ef727c875d',
                'eventId' => '34819677',
                'exEventId' => '49985981351397c256d75ae6c11a30a1',
                'sportId' => '4',
                'tournamentsId' => '34644908',
                'tournamentsName' => "ICC Women's Cricket World Cup",
                'eventName' => 'England W v Sri Lanka W',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-08 06:02:47',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            // Tennis Events
            [
                'id' => 16,
                '_id' => '68e70484dc3e2222add99eac',
                'eventId' => '34824783',
                'exEventId' => '5f390c728c42d365514e7702a7cb0781',
                'sportId' => '2',
                'tournamentsId' => '1581960973',
                'tournamentsName' => 'Santiago de Cali Challenger 2025',
                'eventName' => 'Prado Angelo v Ma Soto',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 00:40:36',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 17,
                '_id' => '68e745ed018482ca99441168',
                'eventId' => '34823062',
                'exEventId' => 'c340b51a63adc9f2c4b28a5f27a6b021',
                'sportId' => '4',
                'tournamentsId' => '1576035889',
                'tournamentsName' => 'One Day Internationals',
                'eventName' => 'Afghanistan v Bangladesh',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:19:41',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            // Basketball Events
            [
                'id' => 18,
                '_id' => '68e7481f8c60f2ef727d1bef',
                'eventId' => '34823837',
                'exEventId' => 'c4815b75b9a43a86e25f507a7fedf71e',
                'sportId' => '7522',
                'tournamentsId' => '1576144433',
                'tournamentsName' => 'German BBL',
                'eventName' => 'FC Bayern Munchen v Bamberg Baskets',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:29:03',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 19,
                '_id' => '68e7482adc3e2222add9c483',
                'eventId' => '34821055',
                'exEventId' => '2428901ddaaf14f6854be58592bc0b09',
                'sportId' => '7522',
                'tournamentsId' => '1576144433',
                'tournamentsName' => 'German BBL',
                'eventName' => 'MBC v Ulm Baskets',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:29:14',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 20,
                '_id' => '68e7482ff165840e0e12294f',
                'eventId' => '34820744',
                'exEventId' => 'f4df229aab4f2834953075cbd706e9e5',
                'sportId' => '7522',
                'tournamentsId' => '1576144433',
                'tournamentsName' => 'German BBL',
                'eventName' => 'Wurzburg Baskets v ALBA Berlin',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:29:19',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 21,
                '_id' => '68e74834f165840e0e122968',
                'eventId' => '34821171',
                'exEventId' => 'e02c8f6f036d8cd65dea9a2f59c323a4',
                'sportId' => '7522',
                'tournamentsId' => '1576144433',
                'tournamentsName' => 'German BBL',
                'eventName' => 'Gladiators Trier v Basketball Lowen Braunschweig',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:29:24',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 22,
                '_id' => '68e7483bf165840e0e12296b',
                'eventId' => '34821152',
                'exEventId' => '929e59b28bca16422c51116ec1f7c45a',
                'sportId' => '7522',
                'tournamentsId' => '1576144433',
                'tournamentsName' => 'German BBL',
                'eventName' => 'Skyliners Frankfurt v Rasta Vechta',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:29:31',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 23,
                '_id' => '68e749d28c60f2ef727d1c38',
                'eventId' => '34814814',
                'exEventId' => 'ac0ae07e72379500c471153ab8f5d6d4',
                'sportId' => '7522',
                'tournamentsId' => '1576144528',
                'tournamentsName' => 'French ProA League',
                'eventName' => 'JDA Dijon Basket v Cholet Basket',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 05:36:18',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            // Soccer Events
            [
                'id' => 24,
                '_id' => '68e7dc19018482ca99444733',
                'eventId' => '34826706',
                'exEventId' => '61e0168b5041e118f8d4ce7d7abd9a48',
                'sportId' => '4',
                'tournamentsId' => '34644908',
                'tournamentsName' => "ICC Women's Cricket World Cup",
                'eventName' => 'India W v Australia W',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-09 16:00:25',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 25,
                '_id' => '68e85b295d170f25d939e975',
                'eventId' => '34827162',
                'exEventId' => '820bd0947428ae0d0a8d6ad99c5a5a7d',
                'sportId' => '2',
                'tournamentsId' => '34786742',
                'tournamentsName' => 'ATP Shanghai 2025',
                'eventName' => 'Djokovic v Vacherot',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 01:02:33',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 26,
                '_id' => '68e85ca52ffd15841e12c055',
                'eventId' => '34828293',
                'exEventId' => '09cc278b6efa833424fedc350f10e25c',
                'sportId' => '2',
                'tournamentsId' => '1581960973',
                'tournamentsName' => 'Santiago de Cali Challenger 2025',
                'eventName' => 'Jua Varillas v Go Bueno',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 01:08:53',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 27,
                '_id' => '68e85ce45d170f25d939e9c8',
                'eventId' => '34828153',
                'exEventId' => 'c05b813d7f0c02b0870485b989784e02',
                'sportId' => '2',
                'tournamentsId' => '1581962971',
                'tournamentsName' => 'Valencia Challenger 2025',
                'eventName' => 'Choinski v Henri Squire',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 01:09:56',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 28,
                '_id' => '68e8939473b37bc623332f3b',
                'eventId' => '34826080',
                'exEventId' => '5e5b96c53d60c5536ced78a875331448',
                'sportId' => '7522',
                'tournamentsId' => '28047999',
                'tournamentsName' => 'Australian NBL',
                'eventName' => 'Illawarra Hawks v Brisbane Bullets',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 05:03:16',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 29,
                '_id' => '68e893952ffd15841e12da7a',
                'eventId' => '34826092',
                'exEventId' => 'bbd46a5a6aaf41038aad8da57e7b7ed8',
                'sportId' => '7522',
                'tournamentsId' => '28047999',
                'tournamentsName' => 'Australian NBL',
                'eventName' => 'New Zealand Breakers v SE Melbourne Phoenix',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 05:03:17',
                'updated_at' => now(),
                'created_at' => now(),
            ],
            [
                'id' => 30,
                '_id' => '68e89399da63bea60e8e331c',
                'eventId' => '34828572',
                'exEventId' => '7b9b51d6a898ee8c8018231c433c9c05',
                'sportId' => '7522',
                'tournamentsId' => '28047999',
                'tournamentsName' => 'Australian NBL',
                'eventName' => 'Adelaide 36ers v Sydney Kings',
                'highlight' => false,
                'quicklink' => false,
                'popular' => false,
                'IsSettle' => 0,
                'IsVoid' => 0,
                'IsUnsettle' => 1,
                'dataSwitch' => 0,
                'createdAt' => '2025-10-10 05:03:21',
                'updated_at' => now(),
                'created_at' => now(),
            ],
        ];

        // Insert events using raw DB query for better performance
        $events = array_map(function ($event) {
            return Arr::except($event, ['id']);
        }, $events);

        DB::table('events')->insert($events);

        $sequence = DB::selectOne("SELECT pg_get_serial_sequence('events', 'id') AS seq")->seq ?? 'events_id_seq';
        DB::statement("SELECT setval('{$sequence}', COALESCE(MAX(id), 0)) FROM events");
    }
}