<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MarketListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $markets = [
            [
                '_id' => '68ef5aaf610777641f275158',
                'eventName' => 'South Australia Redbacks v Queensland Bulls',
                'exEventId' => '704c8badb5db0b4eeae70dbf064ef3f1',
                'exMarketId' => '470eda916c0feca90550ad956fc4252f',
                'isPreBet' => false,
                'marketName' => 'Most Points',
                'marketTime' => '2025-10-16 00:30:00',
                'sportName' => 'Cricket',
                'tournamentsName' => 'Sheffield Shield',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => '2025-10-17 06:00:55',
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'a1b2c3d4e5f6789012345678901234ab',
                'eventName' => 'Manchester United vs Liverpool',
                'exEventId' => 'a1b2c3d4e5f6789012345678901234ab',
                'exMarketId' => 'b2c3d4e5f6789012345678901234abcd',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(2),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'b2c3d4e5f6789012345678901234abcd',
                'eventName' => 'Manchester United vs Liverpool',
                'exEventId' => 'a1b2c3d4e5f6789012345678901234ab',
                'exMarketId' => 'c3d4e5f6789012345678901234abcdef',
                'isPreBet' => true,
                'marketName' => 'Over/Under 2.5 Goals',
                'marketTime' => Carbon::now()->addHours(2),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'total_goals',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'c3d4e5f6789012345678901234abcdef',
                'eventName' => 'Barcelona vs Real Madrid',
                'exEventId' => 'd4e5f6789012345678901234abcdef01',
                'exMarketId' => 'e5f6789012345678901234abcdef0123',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(4),
                'sportName' => 'Soccer',
                'tournamentsName' => 'La Liga',
                'type' => 'match_odds',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'd4e5f6789012345678901234abcdef01',
                'eventName' => 'Federer vs Nadal',
                'exEventId' => 'f6789012345678901234abcdef012345',
                'exMarketId' => '789012345678901234abcdef01234567',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(6),
                'sportName' => 'Tennis',
                'tournamentsName' => 'Wimbledon',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'e5f6789012345678901234abcdef0123',
                'eventName' => 'Federer vs Nadal',
                'exEventId' => 'f6789012345678901234abcdef012345',
                'exMarketId' => '89012345678901234abcdef012345678',
                'isPreBet' => true,
                'marketName' => 'Total Sets',
                'marketTime' => Carbon::now()->addHours(6),
                'sportName' => 'Tennis',
                'tournamentsName' => 'Wimbledon',
                'type' => 'total_sets',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => 'f6789012345678901234abcdef012345',
                'eventName' => 'India vs Australia',
                'exEventId' => '9012345678901234abcdef0123456789',
                'exMarketId' => '012345678901234abcdef01234567890a',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(8),
                'sportName' => 'Cricket',
                'tournamentsName' => 'World Cup',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '789012345678901234abcdef01234567',
                'eventName' => 'India vs Australia',
                'exEventId' => '9012345678901234abcdef0123456789',
                'exMarketId' => '12345678901234abcdef01234567890ab',
                'isPreBet' => true,
                'marketName' => 'Total Runs',
                'marketTime' => Carbon::now()->addHours(8),
                'sportName' => 'Cricket',
                'tournamentsName' => 'World Cup',
                'type' => 'total_runs',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '89012345678901234abcdef012345678',
                'eventName' => 'Lakers vs Warriors',
                'exEventId' => '2345678901234abcdef01234567890abc',
                'exMarketId' => '345678901234abcdef01234567890abcd',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(10),
                'sportName' => 'Basketball',
                'tournamentsName' => 'NBA',
                'type' => 'match_odds',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '9012345678901234abcdef0123456789',
                'eventName' => 'Lakers vs Warriors',
                'exEventId' => '2345678901234abcdef01234567890abc',
                'exMarketId' => '45678901234abcdef01234567890abcde',
                'isPreBet' => true,
                'marketName' => 'Total Points',
                'marketTime' => Carbon::now()->addHours(10),
                'sportName' => 'Basketball',
                'tournamentsName' => 'NBA',
                'type' => 'total_points',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '012345678901234abcdef01234567890a',
                'eventName' => 'Tyson vs Ali',
                'exEventId' => '5678901234abcdef01234567890abcdef',
                'exMarketId' => '678901234abcdef01234567890abcdef0',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(12),
                'sportName' => 'Boxing',
                'tournamentsName' => 'Heavyweight Championship',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '12345678901234abcdef01234567890ab',
                'eventName' => 'Tyson vs Ali',
                'exEventId' => '5678901234abcdef01234567890abcdef',
                'exMarketId' => '78901234abcdef01234567890abcdef01',
                'isPreBet' => true,
                'marketName' => 'Round Betting',
                'marketTime' => Carbon::now()->addHours(12),
                'sportName' => 'Boxing',
                'tournamentsName' => 'Heavyweight Championship',
                'type' => 'round_betting',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '2345678901234abcdef01234567890abc',
                'eventName' => 'Formula 1 Grand Prix',
                'exEventId' => '8901234abcdef01234567890abcdef012',
                'exMarketId' => '901234abcdef01234567890abcdef0123',
                'isPreBet' => false,
                'marketName' => 'Race Winner',
                'marketTime' => Carbon::now()->addHours(14),
                'sportName' => 'Formula 1',
                'tournamentsName' => 'Formula 1',
                'type' => 'race_winner',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '345678901234abcdef01234567890abcd',
                'eventName' => 'Formula 1 Grand Prix',
                'exEventId' => '8901234abcdef01234567890abcdef012',
                'exMarketId' => '01234abcdef01234567890abcdef01234',
                'isPreBet' => true,
                'marketName' => 'Podium Finish',
                'marketTime' => Carbon::now()->addHours(14),
                'sportName' => 'Formula 1',
                'tournamentsName' => 'Formula 1',
                'type' => 'podium_finish',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '45678901234abcdef01234567890abcde',
                'eventName' => 'Chelsea vs Arsenal',
                'exEventId' => '1234abcdef01234567890abcdef012345',
                'exMarketId' => '234abcdef01234567890abcdef0123456',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(16),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
            [
                '_id' => '5678901234abcdef01234567890abcdef',
                'eventName' => 'Chelsea vs Arsenal',
                'exEventId' => '1234abcdef01234567890abcdef012345',
                'exMarketId' => '34abcdef01234567890abcdef01234567',
                'isPreBet' => true,
                'marketName' => 'Both Teams to Score',
                'marketTime' => Carbon::now()->addHours(16),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'both_teams_score',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => null,
                'isCompleted' => false,
            ],
        ];

        DB::table('market_lists')->insert($markets);
    }
}