<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MarketListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $markets = [
            [
                '_id' => 'market_001',
                'eventName' => 'Manchester United vs Liverpool',
                'exEventId' => 'evt_001',
                'exMarketId' => 'mkt_001',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(2),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_002',
                'eventName' => 'Manchester United vs Liverpool',
                'exEventId' => 'evt_001',
                'exMarketId' => 'mkt_002',
                'isPreBet' => true,
                'marketName' => 'Over/Under 2.5 Goals',
                'marketTime' => Carbon::now()->addHours(2),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'total_goals',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_003',
                'eventName' => 'Barcelona vs Real Madrid',
                'exEventId' => 'evt_002',
                'exMarketId' => 'mkt_003',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(4),
                'sportName' => 'Soccer',
                'tournamentsName' => 'La Liga',
                'type' => 'match_odds',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_004',
                'eventName' => 'Federer vs Nadal',
                'exEventId' => 'evt_003',
                'exMarketId' => 'mkt_004',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(6),
                'sportName' => 'Tennis',
                'tournamentsName' => 'Wimbledon',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_005',
                'eventName' => 'Federer vs Nadal',
                'exEventId' => 'evt_003',
                'exMarketId' => 'mkt_005',
                'isPreBet' => true,
                'marketName' => 'Total Sets',
                'marketTime' => Carbon::now()->addHours(6),
                'sportName' => 'Tennis',
                'tournamentsName' => 'Wimbledon',
                'type' => 'total_sets',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_006',
                'eventName' => 'India vs Australia',
                'exEventId' => 'evt_004',
                'exMarketId' => 'mkt_006',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(8),
                'sportName' => 'Cricket',
                'tournamentsName' => 'World Cup',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_007',
                'eventName' => 'India vs Australia',
                'exEventId' => 'evt_004',
                'exMarketId' => 'mkt_007',
                'isPreBet' => true,
                'marketName' => 'Total Runs',
                'marketTime' => Carbon::now()->addHours(8),
                'sportName' => 'Cricket',
                'tournamentsName' => 'World Cup',
                'type' => 'total_runs',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_008',
                'eventName' => 'Lakers vs Warriors',
                'exEventId' => 'evt_005',
                'exMarketId' => 'mkt_008',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(10),
                'sportName' => 'Basketball',
                'tournamentsName' => 'NBA',
                'type' => 'match_odds',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_009',
                'eventName' => 'Lakers vs Warriors',
                'exEventId' => 'evt_005',
                'exMarketId' => 'mkt_009',
                'isPreBet' => true,
                'marketName' => 'Total Points',
                'marketTime' => Carbon::now()->addHours(10),
                'sportName' => 'Basketball',
                'tournamentsName' => 'NBA',
                'type' => 'total_points',
                'isLive' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_010',
                'eventName' => 'Tyson vs Ali',
                'exEventId' => 'evt_006',
                'exMarketId' => 'mkt_010',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(12),
                'sportName' => 'Boxing',
                'tournamentsName' => 'Heavyweight Championship',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_011',
                'eventName' => 'Tyson vs Ali',
                'exEventId' => 'evt_006',
                'exMarketId' => 'mkt_011',
                'isPreBet' => true,
                'marketName' => 'Round Betting',
                'marketTime' => Carbon::now()->addHours(12),
                'sportName' => 'Boxing',
                'tournamentsName' => 'Heavyweight Championship',
                'type' => 'round_betting',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_012',
                'eventName' => 'Formula 1 Grand Prix',
                'exEventId' => 'evt_007',
                'exMarketId' => 'mkt_012',
                'isPreBet' => false,
                'marketName' => 'Race Winner',
                'marketTime' => Carbon::now()->addHours(14),
                'sportName' => 'HR',
                'tournamentsName' => 'Formula 1',
                'type' => 'race_winner',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_013',
                'eventName' => 'Formula 1 Grand Prix',
                'exEventId' => 'evt_007',
                'exMarketId' => 'mkt_013',
                'isPreBet' => true,
                'marketName' => 'Podium Finish',
                'marketTime' => Carbon::now()->addHours(14),
                'sportName' => 'HR',
                'tournamentsName' => 'Formula 1',
                'type' => 'podium_finish',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_014',
                'eventName' => 'Chelsea vs Arsenal',
                'exEventId' => 'evt_008',
                'exMarketId' => 'mkt_014',
                'isPreBet' => false,
                'marketName' => 'Match Winner',
                'marketTime' => Carbon::now()->addHours(16),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'match_odds',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                '_id' => 'market_015',
                'eventName' => 'Chelsea vs Arsenal',
                'exEventId' => 'evt_008',
                'exMarketId' => 'mkt_015',
                'isPreBet' => true,
                'marketName' => 'Both Teams to Score',
                'marketTime' => Carbon::now()->addHours(16),
                'sportName' => 'Soccer',
                'tournamentsName' => 'Premier League',
                'type' => 'both_teams_score',
                'isLive' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('market_lists')->insert($markets);
    }
}