<?php

return [
    'timezones' => [
        'UTC' => ['name' => 'UTC', 'flag' => '🌐'],
        'America/New_York' => ['name' => 'Eastern Time (US & Canada)', 'flag' => '🇺🇸'],
        'America/Chicago' => ['name' => 'Central Time (US & Canada)', 'flag' => '🇺🇸'],
        'America/Denver' => ['name' => 'Mountain Time (US & Canada)', 'flag' => '🇺🇸'],
        'America/Los_Angeles' => ['name' => 'Pacific Time (US & Canada)', 'flag' => '🇺🇸'],
        'America/Phoenix' => ['name' => 'Arizona', 'flag' => '🇺🇸'],
        'America/Anchorage' => ['name' => 'Alaska', 'flag' => '🇺🇸'],
        'America/Honolulu' => ['name' => 'Hawaii', 'flag' => '🇺🇸'],
        'America/Toronto' => ['name' => 'Toronto', 'flag' => '🇨🇦'],
        'America/Vancouver' => ['name' => 'Vancouver', 'flag' => '🇨🇦'],
        'America/Mexico_City' => ['name' => 'Mexico City', 'flag' => '🇲🇽'],
        'America/Sao_Paulo' => ['name' => 'São Paulo', 'flag' => '🇧🇷'],
        'America/Argentina/Buenos_Aires' => ['name' => 'Buenos Aires', 'flag' => '🇦🇷'],
        'America/Lima' => ['name' => 'Lima', 'flag' => '🇵🇪'],
        'America/Santiago' => ['name' => 'Santiago', 'flag' => '🇨🇱'],
        'Europe/London' => ['name' => 'London', 'flag' => '🇬🇧'],
        'Europe/Paris' => ['name' => 'Paris', 'flag' => '🇫🇷'],
        'Europe/Berlin' => ['name' => 'Berlin', 'flag' => '🇩🇪'],
        'Europe/Rome' => ['name' => 'Rome', 'flag' => '🇮🇹'],
        'Europe/Madrid' => ['name' => 'Madrid', 'flag' => '🇪🇸'],
        'Europe/Amsterdam' => ['name' => 'Amsterdam', 'flag' => '🇳🇱'],
        'Europe/Brussels' => ['name' => 'Brussels', 'flag' => '🇧🇪'],
        'Europe/Vienna' => ['name' => 'Vienna', 'flag' => '🇦🇹'],
        'Europe/Zurich' => ['name' => 'Zurich', 'flag' => '🇨🇭'],
        'Europe/Stockholm' => ['name' => 'Stockholm', 'flag' => '🇸🇪'],
        'Europe/Oslo' => ['name' => 'Oslo', 'flag' => '🇳🇴'],
        'Europe/Copenhagen' => ['name' => 'Copenhagen', 'flag' => '🇩🇰'],
        'Europe/Helsinki' => ['name' => 'Helsinki', 'flag' => '🇫🇮'],
        'Europe/Warsaw' => ['name' => 'Warsaw', 'flag' => '🇵🇱'],
        'Europe/Prague' => ['name' => 'Prague', 'flag' => '🇨🇿'],
        'Europe/Budapest' => ['name' => 'Budapest', 'flag' => '🇭🇺'],
        'Europe/Athens' => ['name' => 'Athens', 'flag' => '🇬🇷'],
        'Europe/Istanbul' => ['name' => 'Istanbul', 'flag' => '🇹🇷'],
        'Europe/Moscow' => ['name' => 'Moscow', 'flag' => '🇷🇺'],
        'Europe/Dublin' => ['name' => 'Dublin', 'flag' => '🇮🇪'],
        'Europe/Lisbon' => ['name' => 'Lisbon', 'flag' => '🇵🇹'],
        'Asia/Dubai' => ['name' => 'Dubai', 'flag' => '🇦🇪'],
        'Asia/Karachi' => ['name' => 'Karachi', 'flag' => '🇵🇰'],
        'Asia/Kolkata' => ['name' => 'Mumbai, New Delhi', 'flag' => '🇮🇳'],
        'Asia/Dhaka' => ['name' => 'Dhaka', 'flag' => '🇧🇩'],
        'Asia/Bangkok' => ['name' => 'Bangkok', 'flag' => '🇹🇭'],
        'Asia/Jakarta' => ['name' => 'Jakarta', 'flag' => '🇮🇩'],
        'Asia/Singapore' => ['name' => 'Singapore', 'flag' => '🇸🇬'],
        'Asia/Kuala_Lumpur' => ['name' => 'Kuala Lumpur', 'flag' => '🇲🇾'],
        'Asia/Manila' => ['name' => 'Manila', 'flag' => '🇵🇭'],
        'Asia/Hong_Kong' => ['name' => 'Hong Kong', 'flag' => '🇭🇰'],
        'Asia/Shanghai' => ['name' => 'Beijing, Shanghai', 'flag' => '🇨🇳'],
        'Asia/Taipei' => ['name' => 'Taipei', 'flag' => '🇹🇼'],
        'Asia/Seoul' => ['name' => 'Seoul', 'flag' => '🇰🇷'],
        'Asia/Tokyo' => ['name' => 'Tokyo', 'flag' => '🇯🇵'],
        'Asia/Yakutsk' => ['name' => 'Yakutsk', 'flag' => '🇷🇺'],
        'Asia/Vladivostok' => ['name' => 'Vladivostok', 'flag' => '🇷🇺'],
        'Australia/Sydney' => ['name' => 'Sydney', 'flag' => '🇦🇺'],
        'Australia/Melbourne' => ['name' => 'Melbourne', 'flag' => '🇦🇺'],
        'Australia/Brisbane' => ['name' => 'Brisbane', 'flag' => '🇦🇺'],
        'Australia/Perth' => ['name' => 'Perth', 'flag' => '🇦🇺'],
        'Australia/Adelaide' => ['name' => 'Adelaide', 'flag' => '🇦🇺'],
        'Pacific/Auckland' => ['name' => 'Auckland', 'flag' => '🇳🇿'],
        'Pacific/Honolulu' => ['name' => 'Honolulu', 'flag' => '🇺🇸'],
        'Africa/Cairo' => ['name' => 'Cairo', 'flag' => '🇪🇬'],
        'Africa/Johannesburg' => ['name' => 'Johannesburg', 'flag' => '🇿🇦'],
        'Africa/Lagos' => ['name' => 'Lagos', 'flag' => '🇳🇬'],
        'Africa/Nairobi' => ['name' => 'Nairobi', 'flag' => '🇰🇪'],
        'Middle East/Riyadh' => ['name' => 'Riyadh', 'flag' => '🇸🇦'],
        'Asia/Riyadh' => ['name' => 'Riyadh', 'flag' => '🇸🇦'],
        'Asia/Tehran' => ['name' => 'Tehran', 'flag' => '🇮🇷'],
        'Asia/Baghdad' => ['name' => 'Baghdad', 'flag' => '🇮🇶'],
        'Asia/Jerusalem' => ['name' => 'Jerusalem', 'flag' => '🇮🇱'],
    ],
];

